spring.application.name=chat-app-backend

spring.data.mongodb.uri=mongodb+srv://gaganprajapati:gagan%408960@chat-app.qixlhsy.mongodb.net/chatapp?retryWrites=true&w=majority

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
groq.api.key=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